["pyproject.toml".tool.poetry.dependencies]


["pyproject.toml".tool.poetry.dev-dependencies]
tox = "^3.15"
pytest = "^6.0"
pytest-cov = "^2.9"
coverage = {version = "^5.1", extras = ["toml"]}
coverage2clover = "^2.0"
wemake-python-styleguide = "^0.14"
black = "^20.8b1"
isort = "^4.3"
flake8 = "^3.8"
pre-commit = "^2.4"
mypy = "^0.780"
nitpick = "^0.22"
