
[nitpick.files.absent]
".isort.cfg" = "Move values to setup.cfg, section [isort]"
".flake8" = "Move values to setup.cfg, section [flake8]"
"mypy.ini" = "Move values to setup.cfg, section [mypy]"
"test" = "Use '/tests' folder instead."

[nitpick.files.present]
".gitignore" = "A project should have `.gitignore` file"
"README.md" = "A project should have `README.md`"
".pre-commit-config.yaml" = "Create the file with the contents below, then run 'pre-commit install'"
"setup.cfg" = "Configure helper tools in this file."

".editorconfig" = "A project should have an editor configuration"
"src" = "Put the source code to the '/src' folder, don't leave it in the root folder."
"tests" = "Put all tests into the '/tests' folder."
