[nitpick.styles]
include = [
#   "flake8.toml",
#   "isort.toml",
#   "darglint.toml"
]

[nitpick]
minimum_version = "0.21.0"


["pyproject.toml".build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"


["pyproject.toml".tool.poetry.dependencies]
python = "^3.6 || ^3.7 || ^3.99"



["pyproject.toml".tool.poetry.dev-dependencies]
tox = "^3.14.6"
pytest = "^5.2"
coverage = {version = "^5.0.4", extras = ["toml"]}
pytest-cov = "^2.8.1"
coverage2clover = "^2.0.1"
wemake-python-styleguide = "^0.14.0"
black = "^19.10b0"
isort = "^4.3.21"
flake8 = "^3.7.9"
pre-commit = "^2.2.0"
mypy = "^0.770"
nitpick = "^0.22.2"


["pyproject.toml".tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

["pyproject.toml".tool.coverage.run]
parallel = true
branch = true
source = ["src"]


["pyproject.toml".tool.coverage.paths]
source = ["src", ".tox/*/site-packages"]


["pyproject.toml".tool.coverage.report]
show_missing = true


[nitpick.files."setup.cfg"]
comma_separated_values = ["flake8.ignore", "flake8.extend-ignore"]



["setup.cfg".flake8]
format="wemake"
exclude = ".tox, tests/*, docs/*"
show-source = true
enable-extensions="G"
max-line-length = 88
extend-ignore = """
    E203,
    Q000,
    WPS305, # discourage string format.
    WPS306, # discourage empty class inheritance, this is not needed for py3
    WPS412, # discourage __init__ with "logic" aka anything but docstring
    WPS410  # discourage __all__ variable for packages
    WPS348  # discourage line starting with '.'
"""



["setup.cfg".isort]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=88
lines_after_imports=2
lines_between_types=1


["setup.cfg".mypy]
plugins = "returns.contrib.mypy.decorator_plugin, pydantic.mypy"
allow_redefinition = false
check_untyped_defs = true
ignore_errors = false
ignore_missing_imports = true
implicit_reexport = false
local_partial_types = true
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true

